---
- name: Configure
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: configure.yml
  vars:
    _common_system_user: "{{ influxdb_exporter_system_user }}"
    _common_system_group: "{{ influxdb_exporter_system_group }}"
  tags:
    - influxdb_exporter
    - configure
    - influxdb_exporter_configure
