---
argument_specs:
  main:
    short_description: "Prometheus SNMP exporter"
    description:
      - "Deploy and manage prometheus L(SNMP exporter,https://github.com/prometheus/snmp_exporter) using ansible."
    author:
      - "Prometheus Community"
    options:
      snmp_exporter_version:
        description: "SNMP exporter package version"
        default: "0.19.0"
      snmp_exporter_web_listen_address:
        description: "Address on which SNMP exporter will be listening"
        default: "0.0.0.0:9116"
      snmp_exporter_config_file:
        description:
          - "If this is empty, role will download snmp.yml file from U(https://github.com/prometheus/snmp_exporter)."
          - "Otherwise this should contain path to file with custom snmp exporter configuration"
