---
- name: Run role
  hosts: all
  any_errors_fatal: true
  roles:
    - prometheus.prometheus.mysqld_exporter
  pre_tasks:
    - name: Create mysqld_exporter cert dir
      ansible.builtin.file:
        path: "{{ mysqld_exporter_tls_server_config.cert_file | dirname }}"
        state: directory
        owner: root
        group: root
        mode: u+rwX,g+rwX,o=rX

    - name: Copy cert and key
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode | default('0644') }}"
      loop:
        - src: "/tmp/tls.cert"
          dest: "{{ mysqld_exporter_tls_server_config.cert_file }}"
        - src: "/tmp/tls.key"
          dest: "{{ mysqld_exporter_tls_server_config.key_file }}"
  vars:
    mysqld_exporter_binary_local_dir: "/tmp/mysqld_exporter-linux-amd64"
    mysqld_exporter_web_listen_address: "127.0.0.1:8080"
    mysqld_exporter_enabled_collectors:
      - slave_hosts
    mysqld_exporter_disabled_collectors:
      - global_variables

    mysqld_exporter_tls_server_config:
      cert_file: /etc/mysqld_exporter/tls.cert
      key_file: /etc/mysqld_exporter/tls.key
    mysqld_exporter_http_server_config:
      http2: true
    mysqld_exporter_basic_auth_users:
      randomuser: examplepassword
