---
- name: Prepare
  hosts: localhost
  gather_facts: false
  vars:
    go_arch: amd64
    mysqld_exporter_version: 0.13.0
  tasks:
    - name: Download mysqld_exporter binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysqld_exporter_version }}/\
              mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        mode: 0644
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      check_mode: false

    - name: Unpack mysqld_exporter binary
      become: false
      ansible.builtin.unarchive:
        src: "/tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ go_arch }}/mysqld_exporter"
      check_mode: false

    - name: Link to mysqld_exporter binaries directory
      become: false
      ansible.builtin.file:
        src: "/tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64"
        dest: "/tmp/mysqld_exporter-linux-amd64"
        state: link
      check_mode: false

    - name: Install pyOpenSSL for certificate generation
      ansible.builtin.pip:
        name: "pyOpenSSL"

    - name: Create private key
      community.crypto.openssl_privatekey:
        path: "/tmp/tls.key"

    - name: Create CSR
      community.crypto.openssl_csr:
        path: "/tmp/tls.csr"
        privatekey_path: "/tmp/tls.key"

    - name: Create certificate
      community.crypto.x509_certificate:
        path: "/tmp/tls.cert"
        csr_path: "/tmp/tls.csr"
        privatekey_path: "/tmp/tls.key"
        provider: selfsigned
