---
provisioner:
  playbooks:
    prepare: "${MOLECULE_PROJECT_DIRECTORY}/../../.config/molecule/alternative/prepare.yml"
  inventory:
    group_vars:
      all:
        fail2ban_exporter_binary_local_dir: "/tmp/fail2ban_exporter-linux-amd64_local"
        fail2ban_exporter_web_listen_address: "127.0.1.1:9191"
        go_arch: amd64
        fail2ban_exporter_version: 0.10.1
        fail2ban_exporter_binary_url: "https://gitlab.com/hectorjsmith/fail2ban-prometheus-exporter/-/releases/v{{ fail2ban_exporter_version }}/downloads/\
                                       fail2ban_exporter_{{ fail2ban_exporter_version }}_linux_{{ go_arch }}.tar.gz"
