---
- name: restart alertmanager
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: alertmanager
    state: restarted

- name: reload alertmanager
  become: true
  ansible.builtin.systemd:
    name: alertmanager
    state: reloaded
