---
- name: Run local preparation
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Download influxdb_exporter binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/influxdb_exporter/releases/download/v{{\
          \ influxdb_exporter_version }}/influxdb_exporter-{{ influxdb_exporter_version }}.linux-{{\
          \ go_arch }}.tar.gz"
        dest: "/tmp/influxdb_exporter-{{ influxdb_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        mode: 0644
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      check_mode: false

    - name: Unpack influxdb_exporter binary
      become: false
      ansible.builtin.unarchive:
        src: "/tmp/influxdb_exporter-{{ influxdb_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/influxdb_exporter-{{ influxdb_exporter_version }}.linux-{{ go_arch\
          \ }}/influxdb_exporter"
      check_mode: false

    - name: Link to influxdb_exporter binaries directory
      become: false
      ansible.builtin.file:
        src: "/tmp/influxdb_exporter-{{ influxdb_exporter_version }}.linux-amd64"
        dest: "/tmp/influxdb_exporter-linux-amd64"
        state: link
      check_mode: false
