---
name: Ansible Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint roles
        uses: ansible/ansible-lint-action@main
        with:
          path: roles
