---
name: Check for new upstream releases
on:
  schedule:
    - cron: '21 14 * * *'
  workflow_call:
    inputs:
      role-repos:
        required: true
        type: string
jobs:
  discover-role-repos:
    runs-on: ubuntu-latest
    outputs:
      role-repos: ${{ steps.discovered-role-repos.outputs.result }}
    container:
      image: quay.io/prometheus/golang-builder:base
    steps:
      - uses: actions/checkout@v3

      - name: Get repos for each role
        id: discovered-role-repos
        with:
          cmd: ./.github/scripts/discover_role_repos.sh

  check_for_new_versions:
    runs-on: ubuntu-latest
    needs: discover-role-repos
    permissions:
      contents: write
    container:
      image: quay.io/prometheus/golang-builder:base
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        include: ${{ fromJson(needs.discover-role-repos.outputs.role-repos) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: ./.github/scripts/version_bumper.sh ${{ matrix.repo }} ${{ matrix.role }}
